### ISSUE TITLE
File not found!

### ISSUE THREAD

**Issue by lynxhead** [EvilGreys/Hide-Cobalt-Strike-like-a-PRO#1]
Modify checksum8
----------------------------
The files which containe the algorithm checksum8 of cobaltstrike webserver is (2) files.

"WebServer.java" file in "decompiler_cobaltstrike\cloudstrike".
"CommonUtils.java" file in "decompiler_cobaltstrike\common".

Now click on the Webserver.JAVA file and "ctrl+f" to search for "checksum8" word.

There is only a file named "WebServer$WebListener" which doesn't contain anyword "checksum8". I'm checking with cs4.9.1. But the "CommonUtils.java" have a section  alike the note.

Am i being dump or is there something i'm missing from the procedure ?

**Comment by EvilGreys** [comment]
> ## Изменить контрольную сумму8
> Файлы, содержащие контрольную сумму алгоритма 8 веб-сервера cobaltstrike, составляют (2) файла.
> 
> Файл «WebServer.java» в приложении «decompiler_cobaltstrike\cloudstrike». Файл «CommonUtils.java» в «decompiler_cobaltstrike\common».
> 
> Теперь щелкните файл Webserver.JAVA и нажмите «ctrl+f», чтобы найти слово «checksum8».
> 
> Существует только файл с именем «WebServer$WebListener», который не содержит слова «checksum8». Проверяю cs4.9.1. Но в «CommonUtils.java» есть раздел, похожий на примечание.
> 
> Меня сбрасывают или мне чего-то не хватает в этой процедуре?

With the release of the new version of Cobalt-Strike, we will put this in the repository for public access.

**Comment by EvilGreys** [comment]
> > ## Изменить контрольную сумму8
> > Файлы, содержащие контрольную сумму алгоритма 8 веб-сервера Cobaltstrike, составляют (2) файла.
> > Файл «WebServer.java» в приложении «decompiler_cobaltstrike\cloudstrike». Файл «CommonUtils.java» в «decompiler_cobaltstrike\common».
> > Теперь щелкните файл Webserver.JAVA и нажмите «ctrl+f», чтобы найти слово «checksum8».
> > Существует только файл с именем «WebServer$WebListener», который не содержит слова «checksum8». Проверяю cs4.9.1. Но в «CommonUtils.java» есть раздел, похожий на примечание.
> > Меня сбрасывают или мне чего-то не хватает в этой процедуре?
> 

or you can get ready-made versions on a paid basis, for this you need to send a request by email.
